<?php

namespace Modules\Salary\Database\Seeders;

use Illuminate\Database\Seeder;
use Modules\Salary\Models\SalaryComponent;

class SalaryComponentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $components = [
            // ==================== EARNING COMPONENTS ====================
            [
                'name'               => 'Basic Salary',
                'type'               => 'Earning',
                'category'           => 'Basic',
                'calculation_type'   => 'Fixed',
                'default_value'      => 0,
                'formula_expression' => null,
                'is_taxable'         => true,
                'is_pf_basis'        => true,
                'is_active'          => true,
                'show_in_slip'       => true,
                'display_order'      => 1,
            ],
            [
                'name'               => 'House Rent Allowance',
                'type'               => 'Earning',
                'category'           => 'Allowance',
                'calculation_type'   => 'Percentage of Basic',
                'default_value'      => 50,
                'formula_expression' => null,
                'is_taxable'         => true,
                'is_pf_basis'        => false,
                'is_active'          => true,
                'show_in_slip'       => true,
                'display_order'      => 2,
            ],
            [
                'name'               => 'Medical Allowance',
                'type'               => 'Earning',
                'category'           => 'Allowance',
                'calculation_type'   => 'Fixed',
                'default_value'      => 1500,
                'formula_expression' => null,
                'is_taxable'         => false,
                'is_pf_basis'        => false,
                'is_active'          => true,
                'show_in_slip'       => true,
                'display_order'      => 3,
            ],
            [
                'name'               => 'Conveyance Allowance',
                'type'               => 'Earning',
                'category'           => 'Allowance',
                'calculation_type'   => 'Fixed',
                'default_value'      => 500,
                'formula_expression' => null,
                'is_taxable'         => false,
                'is_pf_basis'        => false,
                'is_active'          => true,
                'show_in_slip'       => true,
                'display_order'      => 4,
            ],
            [
                'name'               => 'Dearness Allowance',
                'type'               => 'Earning',
                'category'           => 'Allowance',
                'calculation_type'   => 'Fixed',
                'default_value'      => 2000,
                'formula_expression' => null,
                'is_taxable'         => true,
                'is_pf_basis'        => true,
                'is_active'          => true,
                'show_in_slip'       => true,
                'display_order'      => 5,
            ],
            [
                'name'               => 'Special Allowance',
                'type'               => 'Earning',
                'category'           => 'Allowance',
                'calculation_type'   => 'Fixed',
                'default_value'      => 0,
                'formula_expression' => null,
                'is_taxable'         => true,
                'is_pf_basis'        => false,
                'is_active'          => true,
                'show_in_slip'       => true,
                'display_order'      => 6,
            ],
            [
                'name'               => 'City Compensatory Allowance',
                'type'               => 'Earning',
                'category'           => 'Allowance',
                'calculation_type'   => 'Fixed',
                'default_value'      => 1000,
                'formula_expression' => null,
                'is_taxable'         => true,
                'is_pf_basis'        => false,
                'is_active'          => true,
                'show_in_slip'       => true,
                'display_order'      => 7,
            ],

            // ==================== DEDUCTION COMPONENTS ====================
            [
                'name'               => 'Provident Fund (PF)',
                'type'               => 'Deduction',
                'category'           => 'PF',
                'calculation_type'   => 'Percentage of Basic',
                'default_value'      => 12,
                'formula_expression' => null,
                'is_taxable'         => false,
                'is_pf_basis'        => false,
                'is_active'          => true,
                'show_in_slip'       => true,
                'display_order'      => 10,
            ],
            [
                'name'               => 'Employee State Insurance (ESI)',
                'type'               => 'Deduction',
                'category'           => 'Insurance',
                'calculation_type'   => 'Percentage of Gross',
                'default_value'      => 0.75,
                'formula_expression' => null,
                'is_taxable'         => false,
                'is_pf_basis'        => false,
                'is_active'          => true,
                'show_in_slip'       => true,
                'display_order'      => 11,
            ],
            [
                'name'               => 'Professional Tax',
                'type'               => 'Deduction',
                'category'           => 'Tax',
                'calculation_type'   => 'Fixed',
                'default_value'      => 200,
                'formula_expression' => null,
                'is_taxable'         => false,
                'is_pf_basis'        => false,
                'is_active'          => true,
                'show_in_slip'       => true,
                'display_order'      => 12,
            ],
            [
                'name'               => 'Income Tax (TDS)',
                'type'               => 'Deduction',
                'category'           => 'Tax',
                'calculation_type'   => 'Percentage of Gross',
                'default_value'      => 10,
                'formula_expression' => null,
                'is_taxable'         => false,
                'is_pf_basis'        => false,
                'is_active'          => true,
                'show_in_slip'       => true,
                'display_order'      => 13,
            ],
            [
                'name'               => 'Loan Deduction',
                'type'               => 'Deduction',
                'category'           => 'Loan',
                'calculation_type'   => 'Fixed',
                'default_value'      => 0,
                'formula_expression' => null,
                'is_taxable'         => false,
                'is_pf_basis'        => false,
                'is_active'          => true,
                'show_in_slip'       => true,
                'display_order'      => 14,
            ],
            [
                'name'               => 'Health Insurance Premium',
                'type'               => 'Deduction',
                'category'           => 'Insurance',
                'calculation_type'   => 'Fixed',
                'default_value'      => 0,
                'formula_expression' => null,
                'is_taxable'         => false,
                'is_pf_basis'        => false,
                'is_active'          => true,
                'show_in_slip'       => true,
                'display_order'      => 15,
            ],
            [
                'name'               => 'Other Deductions',
                'type'               => 'Deduction',
                'category'           => 'Other',
                'calculation_type'   => 'Fixed',
                'default_value'      => 0,
                'formula_expression' => null,
                'is_taxable'         => false,
                'is_pf_basis'        => false,
                'is_active'          => true,
                'show_in_slip'       => true,
                'display_order'      => 16,
            ],

            // ==================== REIMBURSEMENT COMPONENTS ====================
            [
                'name'               => 'Travel Reimbursement',
                'type'               => 'Reimbursement',
                'category'           => 'Allowance',
                'calculation_type'   => 'Fixed',
                'default_value'      => 0,
                'formula_expression' => null,
                'is_taxable'         => false,
                'is_pf_basis'        => false,
                'is_active'          => true,
                'show_in_slip'       => true,
                'display_order'      => 20,
            ],
            [
                'name'               => 'Food Reimbursement',
                'type'               => 'Reimbursement',
                'category'           => 'Allowance',
                'calculation_type'   => 'Fixed',
                'default_value'      => 0,
                'formula_expression' => null,
                'is_taxable'         => false,
                'is_pf_basis'        => false,
                'is_active'          => true,
                'show_in_slip'       => true,
                'display_order'      => 21,
            ],

            // ==================== BONUS COMPONENTS ====================
            [
                'name'               => 'Festival Bonus',
                'type'               => 'Bonus',
                'category'           => 'Bonus',
                'calculation_type'   => 'Fixed',
                'default_value'      => 0,
                'formula_expression' => null,
                'is_taxable'         => true,
                'is_pf_basis'        => false,
                'is_active'          => true,
                'show_in_slip'       => true,
                'display_order'      => 30,
            ],
            [
                'name'               => 'Performance Bonus',
                'type'               => 'Bonus',
                'category'           => 'Bonus',
                'calculation_type'   => 'Formula',
                'default_value'      => 0,
                'formula_expression' => '(basic * performance_rating) / 100',
                'is_taxable'         => true,
                'is_pf_basis'        => false,
                'is_active'          => true,
                'show_in_slip'       => true,
                'display_order'      => 31,
            ],
            [
                'name'               => 'Annual Bonus',
                'type'               => 'Bonus',
                'category'           => 'Bonus',
                'calculation_type'   => 'Percentage of Basic',
                'default_value'      => 100,
                'formula_expression' => null,
                'is_taxable'         => true,
                'is_pf_basis'        => false,
                'is_active'          => true,
                'show_in_slip'       => true,
                'display_order'      => 32,
            ],
        ];

        foreach ($components as $component) {
            SalaryComponent::updateOrCreate(
                ['name' => $component['name']],
                $component
            );
        }
    }
}